from fpdf import FPDF
import datetime
import json
import os

class PDFReport(FPDF):
    def header(self):
        # Logo (left)
        logo_path = os.path.join(
            os.path.dirname(__file__),
            '..', '..', '..', 'frontend', 'public',
            'PhotoshopExtension_Image (1).png'
        )
        if os.path.exists(logo_path):
            try:
                self.image(logo_path, x=10, y=8, h=11)
            except:
                pass

        # Title (center)
        self.set_font('Arial', 'B', 14)
        self.set_text_color(0, 0, 0)
        self.cell(0, 10, 'INSPECTION REPORT', 0, 0, 'C')

        # System Name (right)
        self.set_xy(-55, 8)
        self.set_font('Arial', 'I', 11)
        self.set_text_color(90, 90, 90)
        self.cell(45, 10, 'GARUD', 0, 0, 'R')

        # Separator
        self.ln(14)
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(
            0, 10,
            f"Page {self.page_no()}/{{nb}}  |  Generated by GARUD Automated Inspection System",
            0, 0, 'C'
        )

def generate_report(inspection, wagons):
    pdf = PDFReport()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_font('Arial', '', 12)

    # Inspection Details
    # Inspection Details
    train_speed = inspection.get('train_speed')
    if train_speed is None: train_speed = 0.0
    speed_text = f"{train_speed:.1f} km/h" if train_speed > 0 else "N/A"

    pdf.set_fill_color(245, 245, 245)
    pdf.set_draw_color(220, 220, 220)
    pdf.set_font('Arial', 'B', 11)

    pdf.cell(0, 8, "Inspection Overview", 1, 1, 'L', fill=True)

    pdf.set_font('Arial', '', 10)
    pdf.cell(60, 8, f"Inspection ID: #{inspection['id']}", 1)
    pdf.cell(70, 8, f"Video: {inspection['video_name']}", 1)
    pdf.cell(60, 8, f"Date: {inspection['timestamp']}", 1)
    pdf.ln()

    pdf.cell(60, 8, f"Train Speed: {speed_text}", 1)
    pdf.cell(70, 8, f"Total Wagons: {inspection['total_wagons']}", 1)
    pdf.cell(60, 8, "Inspection Mode: Automated", 1)
    pdf.ln(12)

    # Summary Stats & System Health (Side-by-Side)
    ocr_success = len([w for w in wagons if w['ocr_text'] and w['ocr_text'] != "OCR Failed"])
    defects = len([w for w in wagons if w['defects'] != "None"])
    night = len([w for w in wagons if w['is_night']])
    
    # Save current Y
    y_start = pdf.get_y()
    
    box_height = 45
    pdf.set_fill_color(250, 250, 250)
    pdf.rect(10, y_start, 90, box_height, 'DF')
    pdf.rect(110, y_start, 90, box_height, 'DF')
    
    # LEFT COLUMN: Business Stats
    pdf.set_xy(10, y_start)
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(90, 10, "Summary Statistics", 0, 1)
    pdf.set_font('Arial', '', 10)
    pdf.cell(90, 8, f"Successful OCR: {ocr_success}", 0, 1)
    pdf.cell(90, 8, f"Wagons with Defects: {defects}", 0, 1)
    pdf.cell(90, 8, f"Night Conditions: {night}", 0, 1)
    
    # RIGHT COLUMN: System Health (Hardware)
    # Parse metrics
    # Parse metrics
    fps = inspection.get('fps')
    if fps is None: fps = 0.0
    
    res = inspection.get('resolution')
    if res is None: res = 'N/A'
    
    bright = inspection.get('avg_brightness')
    if bright is None: bright = 0.0
    
    blur_stats = inspection.get('blur_stats')
    if blur_stats is None: blur_stats = '{}'
    try:
        blur_hist = json.loads(blur_stats)
    except:
        blur_hist = {}

    pdf.set_xy(110, y_start)
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(90, 10, "System Health (Hardware)", 0, 1)
    
    pdf.set_xy(110, pdf.get_y())
    pdf.set_font('Arial', '', 10)
    pdf.cell(90, 6, f"Camera FPS: {fps:.1f}", 0, 1)
    
    pdf.set_xy(110, pdf.get_y())
    pdf.cell(90, 6, f"Resolution: {res}", 0, 1)
    
    pdf.set_xy(110, pdf.get_y())
    pdf.cell(90, 6, f"Avg Brightness: {bright:.1f} (0-255)", 0, 1)
    
    pdf.set_xy(110, pdf.get_y())
    pdf.cell(90, 6, "Blur Severity Histogram:", 0, 1)
    
    # Mini histogram text
    current_y = pdf.get_y()
    pdf.set_xy(115, current_y)
    pdf.set_font('Courier', '', 9)
    # Sort keys for consistent order if standard bins
    bins = ['<50', '50-100', '100-200', '>200']
    for b in bins:
        count = blur_hist.get(b, 0)
        if count > 0:
            pdf.cell(80, 4, f"{b:<8}: {count}", 0, 1)
            pdf.set_x(115)
            
    # Reset cursor below both columns
    pdf.set_xy(10, y_start + 50)
    pdf.ln(5)

    # Table Header
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(20, 10, 'Index', 1)
    pdf.cell(50, 10, 'OCR Result', 1)
    pdf.cell(30, 10, 'Confidence', 1)
    pdf.cell(30, 10, 'Defects', 1)
    pdf.cell(40, 10, 'Timestamp', 1)
    pdf.ln()

    # Table Rows
    pdf.set_font('Arial', '', 10)
    for wagon in wagons:
        ocr_text = wagon['ocr_text'] or "N/A"
        conf = f"{wagon['ocr_confidence']*100:.1f}%" if wagon['ocr_confidence'] else "0%"
        defects = wagon['defects']
        ts = wagon['timestamp'].split(' ')[1] if ' ' in wagon['timestamp'] else wagon['timestamp']
        
        if ocr_text == "OCR Failed":
            pdf.set_fill_color(255, 235, 235)  # light red
        elif wagon['ocr_confidence'] and wagon['ocr_confidence'] < 0.8:
            pdf.set_fill_color(255, 245, 220)  # amber
        else:
            pdf.set_fill_color(245, 245, 245)  # neutral
        
        pdf.cell(20, 10, str(wagon['wagon_index']), 1, 0, '', True)
        pdf.cell(50, 10, str(ocr_text), 1, 0, '', True)
        pdf.cell(30, 10, conf, 1, 0, '', True)
        pdf.cell(30, 10, str(defects), 1, 0, '', True)
        pdf.cell(40, 10, ts, 1, 1, '', True)

    
    # -----------------------------
    # Visual Inspection Section
    # -----------------------------
    pdf.add_page()
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, "Detailed Visual Inspection", 0, 1, 'L')
    pdf.ln(5)
    
    import os
    
    for wagon in wagons:
        # Check space for card (approx 60mm)
        if pdf.get_y() > 230:
            pdf.add_page()
            pdf.ln(5)

        # Card Start Y (includes padding)
        # Ensure some spacing from previous element
        pdf.ln(5)
        card_start_y = pdf.get_y()
        
        img_height = 38
        
        # Draw Card Border
        # "Before each wagon" logic adaptation:
        # using card_start_y as the top anchor.
        # User formula was y_start - 6. If we assume y_start was "content top", 
        # let's just draw the rect around the content we are about to place.
        # Height = img_height + 22 (38+22=60)
        # We start drawing content at card_start_y.
        # We'll draw the rect slighty above/around.
        
        pdf.set_draw_color(200, 200, 200)
        pdf.rect(10, card_start_y, 190, img_height + 22)
        
        # Header for the Wagon
        # Position slightly inside the rect
        pdf.set_xy(10, card_start_y) # reset X, Y is same
        pdf.set_font('Arial', 'B', 12)
        bg_color = (240, 240, 240)
        pdf.set_fill_color(*bg_color)
        title = f" Wagon #{wagon['wagon_index']} - OCR: {wagon['ocr_text'] or 'N/A'}"
        pdf.cell(190, 8, title, 0, 1, 'L', fill=True) # width 190 to match rect
        
        # Images Row
        y_start = pdf.get_y() + 2 # slight gap below header
        
        img_width = 55
        x_start = 13 # Indent slightly from border (10)
        gap = 5
        
        # Define images to show
        images = [
            ("Original", wagon.get('original_image_path')),
            ("Deblurred", wagon.get('deblurred_image_path')),
            ("OCR Crop", wagon.get('cropped_number_path'))
        ]
        
        current_x = x_start
        
        for label, path in images:
            # Draw Label
            pdf.set_xy(current_x, y_start)
            pdf.set_font('Arial', 'I', 8)
            pdf.cell(img_width, 5, label, 0, 0, 'C')
            
            # Draw Image
            if path and os.path.exists(path):
                try:
                    pdf.image(path, x=current_x, y=y_start+6, w=img_width, h=img_height)
                except Exception as e:
                    pdf.set_xy(current_x, y_start + 20)
                    pdf.set_font('Arial', '', 8)
                    pdf.cell(img_width, 5, "[Image Error]", 0, 0, 'C')
            else:
                # Placeholder Box
                pdf.rect(current_x, y_start+6, img_width, img_height)
                pdf.set_xy(current_x, y_start+20)
                pdf.cell(img_width, 5, "No Image", 0, 0, 'C')
            
            current_x += (img_width + gap)
        
        # Move cursor past the card
        pdf.set_y(card_start_y + img_height + 22)

    return pdf
